### ISSUE TITLE
Remove member-ordering

### ISSUE THREAD

**Issue by brunozoric** [degordian/js-coding-standards#13]
I use regions in the code to sort methods in kind of scopes
- constants
- variables
- base methods ( constructor and some initialization )
- get methods
- set methods
- events ( adding, removing events )
- user interaction ( adding clicks, responding to clicks, etc... )
- etc...

Problem is that public methods cannot be declared after private or protected. This is killing region organisation :/

Pros for regions: code is organised and you can easily find something that has to do with, eg. User interaction

I need cons :)

**Comment by krukru** [comment]
My cons to using regions is that you can achieve the same or similar level of code organisation by breaking up the class into smaller classes

**Comment by vilimco** [comment]
I have to agree with @krukru, I saw that regions tend to lead to really big classes that have a too much logic in them.

**Comment by leovujanic** [comment]
PHP Storm has great support for regions. You can expand and collapse code. Also you can use Structure window and see methods grouped (at least in PHP in TypeScript so-so)

**Comment by krukru** [comment]
Here is an interesting discussion about the topic https://softwareengineering.stackexchange.com/questions/53086/are-regions-an-antipattern-or-code-smell

**Comment by jakagacic** [comment]
@leovujanic I think this is the thing @jewbre mentioned - you shouldn't have that need to collapse code in a class, so my 👍 to leave it as is.

btw. @brunozoric using regions in this way, i think you will also have problem with [this rule](https://palantir.github.io/tslint/rules/adjacent-overload-signatures/) because you won't be able to keep getters and setters separated

**Comment by brunozoric** [comment]
@krukru that topic discusses really idiotic ways of using the regions ( regions in method?! )
about big clases: you can write them without the regions, no? check [this class](https://github.com/DAPowerPlay/paritytrading-node/blob/order-book/src/components/Application.ts) to see example of regions

@jakagacic getters and setters in my case are methods, not "get" and "set" keywords. i agree that they should be grouped as it is defined by that rule ( in region variable getters and setters :P )

**Comment by vilimco** [comment]
@brunozoric why don't you use PHPStorms ordering options for that?
You know that you can define custom groups and define general ordering for all code styles?

As it goes for big classes, regions aren't main reason for big classes, they are actually really non important for the reason how they get created. The bigger problem is that when you have regions, your code seems more organized just because you use structure view in PHPStorm. When I get a PR with 7 regions, I want to kill myself since I now have to review a file that has several logical components (thus breaking single responsibility principle). Is your code really organised? No, it just seems so. :)

For me personally, if you are using IDE properly, regions are more of an excuse to write everything in one file instead of properly separating logic in several different classes or files.

**Comment by krukru** [comment]
Did not get traction, sorry @brunozoric
