### ISSUE TITLE
Double, triple equals in TypeScript

### ISSUE THREAD

**Issue by leovujanic** [degordian/js-coding-standards#15]
Example:
```typescript
 if (process.env.EXCHANGE_IDS == null) {
        throw new Error("EXCHANGE_IDS env missing");
 }
```
This code will work as expected if EXCHANGE_IDS is not set (is undefined). But if I use `===` instead of `==` it will skip throwing the error because undefined is not equal to null when checking strictly.

Do we have the solution on linter base to avoid that kind of errors?

**Comment by krukru** [comment]
The solution is not to use triple `===` for null/undefined checking. Here is a small test that passes
```typescript
     it("Should test null and undefined", function() {
        const nullVar = null;
        const undefVar = undefined;

        expect(nullVar == null).to.be.true;
        expect(nullVar == undefined).to.be.true;
        expect(nullVar === null).to.be.true;
        expect(nullVar === undefined).to.be.false;

        expect(undefVar == null).to.be.true;
        expect(undefVar == undefined).to.be.true;
        expect(undefVar === null).to.be.false;
        expect(undefVar === undefined).to.be.true;

        expect(nullVar == undefVar).to.be.true;
        expect(nullVar === undefVar).to.be.false;
    });
```

The other (better) solution would be to remove null as a legal keyword alltogether and only check for undefined, but we have failed to reach a consensus on this. https://github.com/degordian/js-coding-standards/issues/6

**Comment by jakagacic** [comment]
I hate using == 

Maybe #6 should be reopened as this continues to be an issue.

**Comment by leovujanic** [comment]
I agree with @jakagacic . Tslint rules as title doesn't talk much about the issue, it's to general. Also that issue is labeled as resolved.

**Comment by krukru** [comment]
We can always reopen the discussion. I will update the title

**Comment by bonzzy** [comment]
I am more for `===` because it is clear to everyone what are you checking. Problem with that is that if you expect `null | undefined` then you have to check both.

This can be referenced to [degordian/js-coding-standards/issues/6](https://github.com/degordian/js-coding-standards/issues/6). 

I personally think that we should never use both and therefore using only undefined is better.
[Microsoft/TypeScript/wiki/Coding-guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines)
