### ISSUE TITLE
Class suffix, pros & cons

### ISSUE THREAD

**Issue by bonzzy** [degordian/js-coding-standards#28]
How do you prefer naming your classes. For example you have `User` (model), `User` (interface), `User` (controller). 
Do you think it is a good idea to add sufix like `UserModel`, `UserInterface`, `UserController`?

Typescript imports have problems when you have two classes with same name, because you have to rename that import at the top of the file.
`import User as UserModel`

**Comment by vilimco** [comment]
I found two approaches to this problem, depending on the project file structure:
1. You are using structure by type : your classes are separated into directories named `controllers`, `models`, `services`, etc. In that case you should name them without type suffix. When you are importing them, you are actually using your path as a namespace, so it seems redundant to have it the name. Exceptions are framework dependencies, like Yii2s `*Controller.php` or `*Test.ts` files for tests.
2. You are using structure by feature: your classes are separated into directories named by features: `login`, `kafka`, `db`, etc. In that case, you should name classes by type: `Controller`, `Helper`, `Service`, `Model`, etc. When there is a collision, then you would use `import {xyz as {name}Xzy}`. Again, exceptions are for framework dependencies.

As it goes for interfaces, they should be clear, without any prefixes or suffixes, since you are going to use it like that, i.e.: `SocketService` is an interface, `AxonSocketService` is the implementation, but you are not using it as `AxonSocketService`, you should be using it as `SocketService`.
Same rule would apply for the models.

### Real life
Now, when it comes to my real life code: I am actually naming services, builders, providers and helpers with that suffix. It makes my code much more readable from the standpoint within method or function (you don't have to go to the imports to see where you've imported it from).

I use interfaces without any prefixes or suffixes and concrete implementation have prefix that will explain what type of interface you are implementing (example with `SocketService` - `AxonSocketService`). Models and enums are also without any prefix/suffix.


My 0.0000025BTC@2018-04-14T08:24:46.007Z: we just need to be consistent with what we choose. :)
