### ISSUE TITLE
Null or undefined discussion

### ISSUE THREAD

**Issue by bonzzy** [degordian/js-coding-standards#6]
I think we should think about agreeing on some `typescript` code guides, because there are many different approaches and currently unresolved questions.
For example, should we use `null` or `undefined?` Microsoft says we should use undefined and not null [Coding-guideline](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines).

**Comment by krukru** [comment]
As a personal preference I suggest using null. But the problem with null is that for almost every type you will need to declare `let foo: Foo | null`, which is overhead. 

Is there any way for tsc to ignore this check and assume any complex-type can also be null?

**Comment by bonzzy** [comment]
[Why null is bad](http://www.yegor256.com/2014/05/13/why-null-is-bad.html).
I still think that we should talk about using `null` and I don't think everyone thinks `null` is a good practice.

**Comment by vilimco** [comment]
@bonzzy I would say that your link is completely unrelated to the topic, since same type of error is going to be thrown for `undefined`.

The underlaying problem is that in both cases you have uncontrolled access to something. You should always have accesses control to your stuff, either through `constructor`, default values or checking through `set` method and this is the main cause for all `x is not a property|function of null|undefined` errors.

I like the idea of `null` cause you can strictly check that value (it is a single object in memory and unique by reference) instead of not defining something. As @krukru said, defining nullable classes as `let foo : Foo | null` is a overhead and, from my point of view, unnecessary overhead if you are writing proper code as I mentioned earlier.

**Comment by bonzzy** [comment]
@jewbre I wasn't aware of offline talk so that is why I raised issue 14 days ago, so if everyone agrees to use null than ok 👍
We all have to be on the same page, because if `null` is not defined as a returning type maybe someone won't expect it when calling a method or checking some parameter and typescript won't remind you!
Example of possible error:
```Typescript
function getPerson(): Person {
    if (someLogic === false) {
        return null;
    }
    let person: Person = new Person();
    return person;
}

let person: Person = getPerson();
/**
 * If getPerson() returns null this will throw error and without looking into this method nobody will know if method can return null or not
 */
person.someMethod();

```

Why maybe it is better to use Foo | null : 
```Typescript
function getPerson(): Person | null {
    if (someLogic === false) {
        return null;
    }
    let person: Person = new Person();
    return person;
}

/**
 *  Typescript will warn me that getPerson could return null and won't let me define person type as Person only
 */
let person: Person = getPerson();
```

Some say it is overhead some it is necessary. 
But again if everyone agrees that `objects` can be `null` also, than ok, but we all have to be on the same page and know that.

**Comment by vilimco** [comment]
As I said, nullable classes are pretty much standard in all major languages and it is a general practice to use `return null` for case you described. Adding that overhead does not solve your problem, just makes you write (or autocomplete) extra stuff. The responsibility for your own code and potential bugs is your own. 

I personally always try check returning data to comply to this rule: **don't trust anything outside your own scope**, and I define scope at the lowest possible level (most often, the class I am writing). So everything from outside scope is getting checked.

Since we merged PR already, I would say that that closes #6.

**Comment by bonzzy** [comment]
Not trusting anything outside your own scope doesn't mean that you can't write code someone could trust. 👍

**Comment by vilimco** [comment]
For me it is a personal preference of failing gracefully over failing uncontrollably. It is ok to trust someone blindly, but that just means that your code is easily breakable by even minor change. I can count how many times I burnt myself with blind trust in my own code, my own classes, not to 
mention other peoples. That is why I am pushing stability responsibility to the lowest possible level. 

And in the end, if you are writing stable code, it is going to be trusted by other. But does that mean they should blindly put their whole trust in your code? Definitely not. 

Not to be taken wrongly, these "breaking changes" don't happen that often in your own codebase, but it is still a really good practice to make your units as stable as possible. :)

**Comment by bonzzy** [comment]
I am not suggesting that someone blindly trusts your code, but to trust the typescript compiler and to write types as strictly as possible. 
I think that defining types strictly could help produce less bugs and errors. I know that you should always check everything and not trust anyone, but I also believe that your code should be clean and understandable. 
If someone (and there is a huge group of people who avoid null) uses your code careless typescript compiler **will never fail** if someone trusts your code blindly, but defining that something is null will **always give you an error** if not writing properly on compiling not on runtime!

**Comment by krukru** [comment]
I see the point @bonzzy is making. If you have a method that has the possibility of returning null, then writing ` | null` this will force you to be aware of that fact.

**Comment by bonzzy** [comment]
I suggest that in the future we talk about this kind of problems on github, raising issues as **we already agreed on earlier**! Not everyone can always be on meetings and talk about this kind of stuff offline, but github issue is visible to all and at the end we can always go back and see why we decided to do so.
As pros and cons I suggest that we always give an example where is better and where is not.
